services:
  - type: web
    name: caloriesnap
    runtime: python
    plan: free
    rootDir: caloriesnap
    buildCommand: pip install -r requirements.txt && reflex init
    startCommand: reflex run --env prod --backend-only --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
