services:
  - type: web
    name: caloriesnap
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      reflex init
    startCommand: reflex run --env prod --frontend-port $PORT --backend-host 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"