services:
  - type: web
    name: caloriesnap
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      reflex init
      reflex export --frontend-only --no-zip
    startCommand: reflex run --env prod --backend-host 0.0.0.0 --backend-port 10000
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PORT
        value: "10000"
    healthCheckPath: /
